Custom span name
avnandu/java-redis-client pull request #2
Opened 2018-06-22 22:07 UTC by avnandu

Can customize span name as per user choice

2018-06-25 15:46 UTC, desumera requested changes

2018-06-25 15:46 UTC, desumera commented on opentracing-redis-common/pom.xml
> +    <artifactId>opentracing-redis-common</artifactId>
FYI, they might give feedback that the formatting changed here without any "real" changes - not sure.

2018-06-25 15:46 UTC, desumera commented on opentracing-redis-common/src/main/java/io/opentracing/contrib/redis/common/RedisSpanNameProvider.java
> +                    + ((operationName == null) ? "unknown" : operationName);
Can we add tests for these? I think I'd be nitpicking to ask for these expressions to be in their own method (for sake of nice naming); having tests would illustrate the same point. And then you'd also have tests 😝

2018-06-25 15:46 UTC, desumera commented on opentracing-redis-common/src/main/java/io/opentracing/contrib/redis/common/TracingHelper.java
> +import java.util.*;
No `*` imports!

2018-06-25 15:46 UTC, desumera commented on opentracing-redis-common/src/main/java/io/opentracing/contrib/redis/common/RedisSpanNameProvider.java
> +                    + ((operationName == null) ? "unknown" : operationName);
Actually, it looks like you're testing the Provider in your TracingHelperTest. Let's keep those separate. That way, we can extensively test the Provider, and what's being tested is also clear.

2018-06-25 15:46 UTC, desumera commented on opentracing-redis-common/src/main/java/io/opentracing/contrib/redis/common/TracingHelper.java
> +    public TracingHelper(Tracer tracer, boolean traceWithActiveSpanOnly) {
Figure out how all this got re-ordered

2018-06-25 15:58 UTC, eleduardo commented
Sorry to do this, we might need to go to the master branch and start again to avoid indentation and re-ordering issues :(. Not sure they will take this PR if we keep these...

2018-06-25 20:14 UTC, desumera commented on .settings.xml
> +        </server>
extra spaces!!!!

2018-06-25 20:14 UTC, desumera commented on opentracing-redis-common/src/main/java/io/opentracing/contrib/redis/common/TracingHelper.java
> +  private Function<String, String> spanNameProvider;
Should this be final?

2018-06-25 20:14 UTC, desumera commented on opentracing-redis-common/src/test/java/io/opentracing/contrib/redis/common/RedisSpanNameProviderTest.java
> +    //span = (MockSpan) (helper.buildSpan(get));
Pls remove commented line

2018-06-25 20:14 UTC, desumera commented on opentracing-redis-lettuce/src/main/java/io/opentracing/contrib/redis/lettuce/TracingRedisAsyncCommands.java
> +  private Function<String, String> redisSpanNameProvider;
Should this be final?

2018-06-26 20:09 UTC, desumera approved these changes
Looks good! When you submit the real PR, provide a bit more explanation/justification in the comments.

2018-06-26 21:53 UTC, merged